language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

install:
  - npm install

stages:
  - lint
  - test
  - build

jobs:
  include:
    - stage: lint
      script:
        - npm run lint
        - npm run lint:css
    - stage: test
      script:
        - npm run test
    - stage: build
      script:
        - npm run build
